export const styleSheet={
    container:{
        display:'flex',
        flexDirection:'column',
        backgroundColor:'gray',
        height:'100vh',
        width:'100vw'
    },
    title__container:{
        display:'flex',
        backgroundColor:'blue',
        height:'20%',
        width:'100%',
        alignItems:'center',
        justifyContent:'center'
    },
    form__container:{
        display:'flex',
        flexDirection:'row',
        backgroundColor:'green',
        height:'60%',
        width:'100%'
    },
    left__form:{
        backgroundColor:'pink',
        height:'100%',
        width:'40%'
    },
    right__form:{
        backgroundColor:'black',
        height:'100%',
        width:'60%'
    },
    btn__container:{
        backgroundColor:'yellow',
        height:'20%',
        width:'100%'
    }
}